version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 73aberiv
      POSTGRES_DB: database_for_spring_lesson